openapi: "3.0.3"
info:
  title: "online_diary API"
  description: "online_diary API"
  version: "1.0.0"
servers:
  - url: "https://online_diary"
tags:
  - name: "Студенты"
    description: "Методы для работы со студентами"
paths:
  /student/{group}:
    get:
      summary: "Получить студентов в определенном классе"
      description: ""
      operationId: "1"
      parameters:
        - name: "group"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AverageScoreDto"
  /student:
    put:
      summary: "Изменить оценку студенту"
      description: ""
      operationId: "2"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeRatingDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChangeRatingDto"
    post:
      summary: "Добавить студента"
      description: ""
      operationId: "3"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddStudentDto"
  /student/addItemsAndRatings:
    post:
      summary: "Добавить студенту с предмет и оценку"
      description: ""
      operationId: "4"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddItemRatingDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddItemRatingDto"
components:
  schemas:
    AverageScoreDto:
      type: "object"
      properties:
        family:
          type: "string"
        name:
          type: "string"
        group:
          type: "string"
        averageScore:
          type: "number"
          format: "double"
    ItemRatingDto:
      type: "object"
      properties:
        itemId:
          type: "string"
        rating:
          type: "integer"
          format: "int32"
    ChangeRatingDto:
      type: "object"
      properties:
        family:
          type: "string"
        name:
          type: "string"
        group:
          type: "string"
        totalScore:
          type: "integer"
          format: "int32"
        itemRatings:
          $ref: "#/components/schemas/ItemRatingDto"
    ItemRating:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        itemId:
          type: "string"
        rating:
          type: "integer"
          format: "int32"
        student:
          $ref: "#/components/schemas/Student"
    Student:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        family:
          type: "string"
        name:
          type: "string"
        age:
          type: "integer"
          format: "int32"
        group:
          type: "string"
        totalScore:
          type: "integer"
          format: "int32"
        itemRatings:
          type: "array"
          items:
            $ref: "#/components/schemas/ItemRating"
    AddStudentDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        family:
          type: "string"
        name:
          type: "string"
        age:
          type: "integer"
          format: "int32"
        group:
          type: "string"
    AddItemRatingDto:
      type: "object"
      properties:
        family:
          type: "string"
        name:
          type: "string"
        age:
          type: "integer"
          format: "int32"
        group:
          type: "string"
        itemRatingDto:
          $ref: "#/components/schemas/ItemRatingDto"
  
